/* dermot_palette.h -- auto-generated by globe_convert.py -- do not edit */
#ifndef DERMOT_PALETTE_H
#define DERMOT_PALETTE_H
#include <stdint.h>
#define PALETTE_SIZE 256U
extern const uint8_t dermot_palette[PALETTE_SIZE][3];  /* {R, G, B} per entry */
#endif /* DERMOT_PALETTE_H */
