/* frog_data.h -- auto-generated by globe_convert_gif.py -- do not edit */
#ifndef FROG_DATA_H
#define FROG_DATA_H
#include <stdint.h>
#define FROG_NUM_FRAMES    40U  /* GIF frames */
#define FROG_NUM_COLUMNS   140U /* angular slices per 180 deg sweep */
#define FROG_NUM_LEDS      144U    /* total LEDs per column */
#define FROG_PACKED_BYTES  72U /* bytes per column (2 LEDs per byte) */

/* Per-frame display duration in milliseconds (from GIF timing) */
extern const uint16_t frog_frame_delay_ms[FROG_NUM_FRAMES]; /* {130, 120, 130, 120, 130, 120, 130, 120, 130, 120, 130, 120, 130, 120, 130, 120, 130, 120, 130, 120, 130, 120, 130, 120, 130, 120, 130, 120, 130, 120, 130, 120, 130, 120, 130, 120, 130, 120, 130, 130} */

/* frog[frame][col][byte]: high nibble = even LED, low nibble = odd LED
 * Pass column pointer directly to BuildFrame_4bit(). */
extern const uint8_t frog[FROG_NUM_FRAMES][FROG_NUM_COLUMNS][FROG_PACKED_BYTES];
#endif /* FROG_DATA_H */
