/* frog_palette.h -- auto-generated by globe_convert_gif.py -- do not edit */
#ifndef FROG_PALETTE_H
#define FROG_PALETTE_H
#include <stdint.h>
#define PALETTE_SIZE 16U
extern const uint8_t frog_palette[PALETTE_SIZE][3]; /* {R, G, B} per entry */
#endif /* FROG_PALETTE_H */
