/* vote_data.h -- auto-generated by globe_convert.py -- do not edit */
#ifndef VOTE_DATA_H
#define VOTE_DATA_H
#include <stdint.h>
#define GLOBE_NUM_COLUMNS 140U  /* angular slices per 180 deg sweep */
#define GLOBE_NUM_LEDS    143U     /* total LEDs per column */
/* vote_data[col][led] = palette index, one byte per LED */
extern const uint8_t vote_data[GLOBE_NUM_COLUMNS][GLOBE_NUM_LEDS];
#endif /* VOTE_DATA_H */
