/* lebron_palette.h -- auto-generated by globe_convert.py -- do not edit */
#ifndef LEBRON_PALETTE_H
#define LEBRON_PALETTE_H
#include <stdint.h>
#define PALETTE_SIZE 256U
extern const uint8_t lebron_palette[PALETTE_SIZE][3];  /* {R, G, B} per entry */
#endif /* LEBRON_PALETTE_H */
