/* lebron_data.h -- auto-generated by globe_convert.py -- do not edit */
#ifndef LEBRON_DATA_H
#define LEBRON_DATA_H
#include <stdint.h>
#define GLOBE_NUM_COLUMNS 140U  /* angular slices per 180 deg sweep */
#define GLOBE_NUM_LEDS    143U     /* total LEDs per column */
/* lebron_data[col][led] = palette index, one byte per LED */
extern const uint8_t lebron_data[GLOBE_NUM_COLUMNS][GLOBE_NUM_LEDS];
#endif /* LEBRON_DATA_H */
