/* map_data.h -- auto-generated by globe_convert.py -- do not edit */
#ifndef MAP_DATA_H
#define MAP_DATA_H
#include <stdint.h>
#define GLOBE_NUM_COLUMNS 140U  /* angular slices per 180 deg sweep */
#define GLOBE_NUM_LEDS    143U     /* total LEDs per column */
/* map_data[col][led] = palette index, one byte per LED */
extern const uint8_t map_data[GLOBE_NUM_COLUMNS][GLOBE_NUM_LEDS];
#endif /* MAP_DATA_H */
