/* cat_space_data.h -- auto-generated by globe_convert_gif.py -- do not edit */
#ifndef CAT_SPACE_DATA_H
#define CAT_SPACE_DATA_H
#include <stdint.h>
#define CAT_SPACE_NUM_FRAMES    9U  /* GIF frames */
#define CAT_SPACE_NUM_COLUMNS   140U /* angular slices per 180 deg sweep */
#define CAT_SPACE_NUM_LEDS      144U    /* total LEDs per column */
#define CAT_SPACE_PACKED_BYTES  72U /* bytes per column (2 LEDs per byte) */

/* Per-frame display duration in milliseconds (from GIF timing) */
extern const uint16_t cat_space_frame_delay_ms[CAT_SPACE_NUM_FRAMES]; /* {100, 100, 100, 100, 100, 100, 100, 100, 100} */

/* cat_space[frame][col][byte]: high nibble = even LED, low nibble = odd LED
 * Pass column pointer directly to BuildFrame_4bit(). */
extern const uint8_t cat_space[CAT_SPACE_NUM_FRAMES][CAT_SPACE_NUM_COLUMNS][CAT_SPACE_PACKED_BYTES];
#endif /* CAT_SPACE_DATA_H */
