/* palette.h -- auto-generated by globe_convert.py -- do not edit */
#ifndef PALETTE_H
#define PALETTE_H
#include <stdint.h>
#define PALETTE_SIZE 256U
extern const uint8_t palette[PALETTE_SIZE][3];  /* {R, G, B} per entry */
#endif /* PALETTE_H */
