/* globe_data.h -- auto-generated by globe_convert.py -- do not edit */
#ifndef GLOBE_DATA_H
#define GLOBE_DATA_H
#include <stdint.h>
#define GLOBE_NUM_COLUMNS 140U  /* angular slices per 180 deg sweep */
#define GLOBE_NUM_LEDS    144U     /* total LEDs per column */
/* globe[col][led] = palette index -- pass col ptr to BuildFrame_8bit() */
extern const uint8_t dot[GLOBE_NUM_COLUMNS][GLOBE_NUM_LEDS];
#endif /* GLOBE_DATA_H */
