/* boi_data.h -- auto-generated by globe_convert_gif.py -- do not edit */
#ifndef BOI_DATA_H
#define BOI_DATA_H
#include <stdint.h>
#define BOI_NUM_FRAMES    33U  /* GIF frames */
#define BOI_NUM_COLUMNS   140U /* angular slices per 180 deg sweep */
#define BOI_NUM_LEDS      144U    /* total LEDs per column */
#define BOI_PACKED_BYTES  72U /* bytes per column (2 LEDs per byte) */

/* Per-frame display duration in milliseconds (from GIF timing) */
extern const uint16_t boi_frame_delay_ms[BOI_NUM_FRAMES]; /* {100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100} */

/* boi[frame][col][byte]: high nibble = even LED, low nibble = odd LED
 * Pass column pointer directly to BuildFrame_4bit(). */
extern const uint8_t boi[BOI_NUM_FRAMES][BOI_NUM_COLUMNS][BOI_PACKED_BYTES];
#endif /* BOI_DATA_H */
