/* eye_palette.h -- auto-generated by globe_convert.py -- do not edit */
#ifndef EYE_PALETTE_H
#define EYE_PALETTE_H
#include <stdint.h>
#define PALETTE_SIZE 256U
extern const uint8_t eye_palette[PALETTE_SIZE][3];  /* {R, G, B} per entry */
#endif /* EYE_PALETTE_H */
