/* baby_data.h -- auto-generated by globe_convert_gif.py -- do not edit */
#ifndef BABY_DATA_H
#define BABY_DATA_H
#include <stdint.h>
#define BABY_NUM_FRAMES    57U  /* GIF frames */
#define BABY_NUM_COLUMNS   140U /* angular slices per 180 deg sweep */
#define BABY_NUM_LEDS      144U    /* total LEDs per column */
#define BABY_PACKED_BYTES  72U /* bytes per column (2 LEDs per byte) */

/* Per-frame display duration in milliseconds (from GIF timing) */
extern const uint16_t baby_frame_delay_ms[BABY_NUM_FRAMES]; /* {100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100} */

/* baby[frame][col][byte]: high nibble = even LED, low nibble = odd LED
 * Pass column pointer directly to BuildFrame_4bit(). */
extern const uint8_t baby[BABY_NUM_FRAMES][BABY_NUM_COLUMNS][BABY_PACKED_BYTES];
#endif /* BABY_DATA_H */
