/* cat_space_palette.h -- auto-generated by globe_convert_gif.py -- do not edit */
#ifndef CAT_SPACE_PALETTE_H
#define CAT_SPACE_PALETTE_H
#include <stdint.h>
#define PALETTE_SIZE 16U
extern const uint8_t cat_space_palette[PALETTE_SIZE][3]; /* {R, G, B} per entry */
#endif /* CAT_SPACE_PALETTE_H */
