/* vote_palette.h -- auto-generated by globe_convert.py -- do not edit */
#ifndef VOTE_PALETTE_H
#define VOTE_PALETTE_H
#include <stdint.h>
#define PALETTE_SIZE 256U
extern const uint8_t vote_palette[PALETTE_SIZE][3];  /* {R, G, B} per entry */
#endif /* VOTE_PALETTE_H */
